language: scala

sudo: required

dist: trusty

group: edge

git:
  depth: 9999

jdk:
  - oraclejdk8

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.7
scala_version_213: &scala_version_213 2.13.0-M5

before_install:
 - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

# TODO ceedubs see if we can avoid repeating the version numbers in so many places
# TODO ceedubs why isn't bench/test part of buildJVM?
jobs:
  include:
    - env: TEST="docs"
      script: sbt makeMicrosite

    - env: TEST="linting"
      script: sbt scalastyle fmtCheck

    - &bincompat_check
      env: TEST="binary compatibility"
      script: sbt ++$TRAVIS_SCALA_VERSION validateBC
      scala: *scala_version_211
    - <<: *bincompat_check
      scala: *scala_version_212

    - &scalafix
      env: TEST="scalafix"
      script: cd scalafix && sbt ++$TRAVIS_SCALA_VERSION tests/test
      scala: *scala_version_211
    - <<: *scalafix
      scala: *scala_version_212

    - &jvm_tests
      env: TEST="JVM tests"
      script: sbt ++$TRAVIS_SCALA_VERSION buildJVM bench/test
      scala: *scala_version_211
    - <<: *jvm_tests
      scala: *scala_version_212
    - <<: *jvm_tests
      scala: *scala_version_213

    - &js_tests
      env: TEST="JS tests"
      script: sbt ++$TRAVIS_SCALA_VERSION validateJS && sbt ++$TRAVIS_SCALA_VERSION validateKernelJS && sbt ++$TRAVIS_SCALA_VERSION validateFreeJS
      scala: *scala_version_211
    - <<: *js_tests
      scala: *scala_version_212

    - env: TEST="coverage"
      script: sbt coverage buildJVM bench/test coverageReport && codecov

    - stage: release
      script: echo "this is where I would release"

# TODO ceedubs can some of these installations be changed to only be on the jobs that need them?
# http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install --user codecov
  - gem install jekyll -v 2.5

notifications:
  webhooks:
    urls:
    - ${GITTER_WEBHOOK_URL}
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
    - secure: Kf44XQFpq2QGe3rn98Dsf5Uz3WXzPDralS54co7sqT5oQGs1mYLYZRYz+I75ZSo5ffZ86H7M+AI9YFofqGwAjBixBbqf1tGkUh3oZp2fN3QfqzazGV3HzC+o41zALG5FL+UBaURev9ChQ5fYeTtFB7YAzejHz4y5E97awk934Rg=
    - secure: QbNAu0jCaKrwjJi7KZtYEBA/pYbTJ91Y1x/eLAJpsamswVOvwnThA/TLYuux+oiZQCiDUpBzP3oxksIrEEUAhl0lMtqRFY3MrcUr+si9NIjX8hmoFwkvZ5o1b7pmLF6Vz3rQeP/EWMLcljLzEwsrRXeK0Ei2E4vFpsg8yz1YXJg=
    - TRAVIS_NODE_VERSION="4"

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
    # Pants cache
    - $HOME/.cache

